export const MODULE_GATES = {
  admin: [
    'core.user.manage',
    'core.role.manage',
  ],
  budgeting: [
    'budgeting.cycle.manage',
    'budgeting.header.manage',
    'budgeting.header.approve',
    'budgeting.release.create',
    'budgeting.reservation.create',
    'budgeting.reservation.approve',
  ],
  procurement: [
    'procurement.read',
    'procurement.pr.create',
    'procurement.caf.create',
    'procurement.caf.certify',
    'procurement.ors.create',
    'procurement.ors.requesting_certify',
    'procurement.ors.budget_certify',
    'procurement.po.create',
    'procurement.po.approve',
    'procurement.delegation.manage',
    'procurement.inspection.create',
    'procurement.inspection.accept',
    'procurement.dv.create',
    'procurement.dv.certify',
    'procurement.dv.approve',
    'procurement.dv.release',
  ],
  inventory: [
    'inventory.read',
    'inventory.item.manage',
    'inventory.receipt.manage',
    'inventory.ris.manage',
    'inventory.ris.approve',
    'inventory.ris.issue',
    'inventory.property.manage',
    'inventory.accountability.manage',
    'inventory.physical_count.manage',
    'inventory.dispose.manage',
    'inventory.reports',
  ],
  billing: [
    'billing.read',
    'billing.consumer.manage',
    'billing.meter.manage',
    'billing.rate.manage',
    'billing.reading.manage',
    'billing.period.manage',
    'billing.bill.generate',
    'billing.bill.adjust',
    'billing.payment.collect',
    'billing.payment.void',
    'billing.disconnect.manage',
    'billing.reports',
  ],
  hr: [
    'hr.read',
    'hr.employee.manage',
    'hr.leave.manage',
    'hr.leave.approve',
    'hr.attendance.manage',
    'hr.payroll.manage',
    'hr.payroll.approve',
    'hr.salary.manage',
    'hr.reports',
  ],
  workorder: [
    'workorder.read',
    'workorder.create',
    'workorder.assign',
    'workorder.execute',
    'workorder.verify',
    'workorder.reports',
  ],
  complaint: [
    'complaint.read',
    'complaint.create',
    'complaint.assign',
    'complaint.resolve',
    'complaint.close',
    'complaint.reports',
  ],
  accounting: [
    'accounting.read',
    'accounting.coa.manage',
    'accounting.bank.manage',
    'accounting.jev.create',
    'accounting.jev.post',
    'accounting.jev.void',
    'accounting.period.manage',
    'accounting.reports',
    'accounting.reconcile',
  ],
  reports: [
    'procurement.read',
    'budgeting.read',
  ],
} as const;

export function hasModuleAccess(permissions: Set<string>, mod: keyof typeof MODULE_GATES): boolean {
  return MODULE_GATES[mod].some((code) => permissions.has(code));
}
